name:                pieceTable
version:             0.1.0.0
github:              "wasabi315/pieceTable"
license:             BSD3
author:              "Satoshi Takimoto"
maintainer:          "wasabi.nvim.st@gmail.com"
copyright:           "(c) 2018 Satoshi Takimoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wasabi315/pieceTable#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- fingertree

library:
  source-dirs: src

executables:
  pieceTable:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pieceTable

tests:
  pieceTable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pieceTable
